Adding local storage results in dashboard & fixed dosage color toggle
kristina-voit/capstone-project--vitamed pull request #27
Opened 2022-01-24 16:11 UTC by kristina-voit

Please refer to #22 and #23 

- If a new card is created in appointment/medicine, it will be displayed on the dashboard as well
- the default color of "0" in dosage is now green

NOT working yet: 
- to-dos are not stored in local storage
- Creating new cards will render all cards in one card
- Graph is still only hard-coded

2022-01-25 13:38 UTC, anitaschiller requested changes
Hi Kristina, nice features, I just left some small remarks.
All in all I saw that you have several components that end with "short". I think it would be nice to refactor that in a later step and try to use the same component by controlling the "size" via a prop?

2022-01-26 13:58 UTC, kristina-voit commented on src/components/Events/NewEventShort.jsx
> +  margin: 12px 0px 0px 0px;
Concerning the refactoring: Yes, will do! Added this to my project board as a task for the upcoming days!

2022-01-26 14:01 UTC, kristina-voit commented on src/components/Events/NewEventShort.jsx
> +  margin: 12px 0px 0px 0px;
Concerning the 0px: changed in all files!

2022-01-26 17:15 UTC, kristina-voit commented on src/components/Medicine/Dosage.jsx
> +        <Description color={!color}>
Changed it to isColored!

2022-01-26 17:16 UTC, kristina-voit commented on src/components/Medicine/DosageShort.jsx
> +const Description = styled.p`
No, I will reuse the Dosage-component! Task is on my project-board.

2022-01-26 17:16 UTC, kristina-voit commented on src/components/Medicine/NewMedicineShort.jsx
> +function NewProduct() {
This is indeed a very good question :-) I will check my whole project for naming issues!

2022-01-26 17:17 UTC, kristina-voit commented on src/components/Medicine/NewMedicineShort.jsx
> +
Done!

2022-01-26 17:17 UTC, merged